const e=require("express"),db=require("../db"),a=require("../middleware/auth"),{importProduct}=require("../services/productImporter"),r=e.Router();r.use(a);
async function role(u,p){const q=await db.query(`SELECT CASE WHEN p.owner_id=$2 THEN 'OWNER' ELSE m.role END role FROM projects p LEFT JOIN project_members m ON m.project_id=p.id AND m.user_id=$2 WHERE p.id=$1 AND(p.owner_id=$2 OR m.user_id=$2)LIMIT 1`,[p,u]);return q.rows[0]?.role||null}
function valid(d){if(!d.name)return"Nome obrigatório.";if(d.status==="ESCOLHIDO"&&(!Number(d.found_price)||!d.product_url))return"Escolhido exige preço e link.";if(d.status==="COMPRADO"&&(!Number(d.paid_price)||!d.purchased_at||!d.payment_method))return"Compra exige preço pago, data e pagamento.";return null}
r.post("/import-url",async(q,s)=>{try{s.json(await importProduct(q.body.url))}catch(x){s.status(422).json({error:x.message})}});
r.get("/project/:id",async(q,s)=>{if(!await role(q.user.id,q.params.id))return s.sendStatus(403);s.json((await db.query("SELECT * FROM items WHERE project_id=$1 ORDER BY created_at DESC",[q.params.id])).rows)});
r.post("/",async(q,s)=>{try{let d=q.body,rl=await role(q.user.id,d.project_id);if(!["OWNER","EDITOR"].includes(rl))return s.status(403).json({error:"Sem permissão para editar este projeto."});let er=valid(d);if(er)return s.status(400).json({error:er});let x=await db.query(`INSERT INTO items(project_id,name,description,quantity,planned_price,found_price,paid_price,status,store,product_url,image_url,purchased_at,payment_status,payment_method,installments,notes)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)RETURNING *`,[d.project_id,d.name,d.description||"",+d.quantity||1,+d.planned_price||0,+d.found_price||0,+d.paid_price||0,d.status||"A_ESCOLHER",d.store||"",d.product_url||"",d.image_url||"",d.purchased_at||null,d.payment_status||"NAO_SE_APLICA",d.payment_method||"",+d.installments||1,d.notes||""]);if(+d.found_price>0)await db.query("INSERT INTO price_history(item_id,price)VALUES($1,$2)",[x.rows[0].id,d.found_price]);s.json(x.rows[0])}catch(x){console.error("item-create:",x);s.status(500).json({error:"Não foi possível salvar o produto."})}});
r.put("/:id",async(q,s)=>{try{const cur=await db.query("SELECT * FROM items WHERE id=$1",[q.params.id]);if(!cur.rowCount)return s.status(404).json({error:"Produto não encontrado."});const item=cur.rows[0],rl=await role(q.user.id,item.project_id);if(!["OWNER","EDITOR"].includes(rl))return s.status(403).json({error:"Sem permissão para editar este produto."});let d=q.body;if(Number(d.project_id)!==Number(item.project_id))return s.status(400).json({error:"Não é permitido mover o produto para outro projeto."});let er=valid(d);if(er)return s.status(400).json({error:er});const x=await db.query(`UPDATE items SET name=$1,description=$2,quantity=$3,planned_price=$4,found_price=$5,paid_price=$6,status=$7,store=$8,product_url=$9,image_url=$10,purchased_at=$11,payment_status=$12,payment_method=$13,installments=$14,notes=$15 WHERE id=$16 RETURNING *`,[d.name,d.description||"",+d.quantity||1,+d.planned_price||0,+d.found_price||0,+d.paid_price||0,d.status||"A_ESCOLHER",d.store||"",d.product_url||"",d.image_url||"",d.purchased_at||null,d.payment_status||"NAO_SE_APLICA",d.payment_method||"",+d.installments||1,d.notes||"",q.params.id]);if(+d.found_price>0&&Number(d.found_price)!==Number(item.found_price))await db.query("INSERT INTO price_history(item_id,price)VALUES($1,$2)",[q.params.id,d.found_price]);s.json(x.rows[0])}catch(x){console.error("item-update:",x);s.status(500).json({error:"Não foi possível atualizar o produto."})}});
r.delete("/:id",async(q,s)=>{try{const cur=await db.query("SELECT project_id FROM items WHERE id=$1",[q.params.id]);if(!cur.rowCount)return s.status(404).json({error:"Produto não encontrado."});const rl=await role(q.user.id,cur.rows[0].project_id);if(!["OWNER","EDITOR"].includes(rl))return s.status(403).json({error:"Sem permissão para excluir este produto."});await db.query("DELETE FROM items WHERE id=$1",[q.params.id]);s.json({ok:true})}catch(x){console.error("item-delete:",x);s.status(500).json({error:"Não foi possível excluir o produto."})}});
module.exports=r;
